tasks:
  - name: Setup Terraform
    init: |
      wget https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
      unzip terraform_1.9.5_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      terraform -v
