AWSTemplateFormatVersion: 2010-09-09
Description: Create a role with S3 access to a specific bucket

Parameters:
  BucketName:
    Type: String
    Default: "my-sts-lab-bucket"

Resources:
  StsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MySTSRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource:
                  - !Sub "arn:aws:s3:::${BucketName}"
                  - !Sub "arn:aws:s3:::${BucketName}/*"