#!/usr/bin/env bash

yq -o json policy.yml > policy.json

aws iam create-policy-version \
    --policy-arn arn:aws:iam::354918366000:policy/my-lab-policy \
    --policy-document "$(yq -o json policy.yml) \
    --set-as-default