AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::AWS::Serverless-2016-10-31
Description: Sns Basic
Resources:
  SNSTopic:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-sns-topic.html
    Type: AWS::SNS::Topic
  Lambda:
    # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.12
      PackageType: Zip 
      InlineCode: |
        def handler(event, context):
            message = 'Hello {} {}!'.format(event['first_name'], event['last_name '])
            print("Log this for me")
            return {
                'message': message
            ｝
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref SNSTopic
